// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DND_Screen

#include "../ui.h"

void ui_comp_NumPad_create_hook( lv_obj_t * comp)
{
}
