// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DND_Screen

#ifndef _UI_COMP_NUMPAD_H
#define _UI_COMP_NUMPAD_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT NumPad
#define UI_COMP_NUMPAD_NUMPAD 0
#define _UI_COMP_NUMPAD_NUM 1
lv_obj_t *ui_NumPad_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
