// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DND_Screen

#include "../ui.h"


// COMPONENT NumPad

lv_obj_t *ui_NumPad_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_NumPad;
cui_NumPad = lv_keyboard_create(comp_parent);
lv_keyboard_set_mode(cui_NumPad,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( cui_NumPad, 315);
lv_obj_set_height( cui_NumPad, 251);
lv_obj_set_x( cui_NumPad, -81 );
lv_obj_set_y( cui_NumPad, 31 );
lv_obj_set_align( cui_NumPad, LV_ALIGN_CENTER );

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_NUMPAD_NUM);
children[UI_COMP_NUMPAD_NUMPAD] = cui_NumPad;
lv_obj_add_event_cb(cui_NumPad, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_NumPad, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_NumPad_create_hook(cui_NumPad);
return cui_NumPad; 
}

