// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DND_Screen

#include "../ui.h"

void ui_Health_Screen_screen_init(void)
{
ui_Health_Screen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Health_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_Health_Screen, &ui_img_wood_paneling_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_WholeScreen = lv_obj_create(ui_Health_Screen);
lv_obj_remove_style_all(ui_WholeScreen);
lv_obj_set_width( ui_WholeScreen, 774);
lv_obj_set_height( ui_WholeScreen, 468);
lv_obj_set_align( ui_WholeScreen, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_WholeScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MainScreen = lv_obj_create(ui_WholeScreen);
lv_obj_remove_style_all(ui_MainScreen);
lv_obj_set_width( ui_MainScreen, 780);
lv_obj_set_height( ui_MainScreen, 468);
lv_obj_set_align( ui_MainScreen, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_MainScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempHPPanel = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_TempHPPanel, 300);
lv_obj_set_height( ui_TempHPPanel, 65);
lv_obj_set_x( ui_TempHPPanel, 28 );
lv_obj_set_y( ui_TempHPPanel, -40 );
lv_obj_set_align( ui_TempHPPanel, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TempHPPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_outline_color(ui_TempHPPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TempHPPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_TempHPPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_TempHPPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea1 = lv_textarea_create(ui_TempHPPanel);
lv_obj_set_width( ui_TextArea1, 159);
lv_obj_set_height( ui_TextArea1, LV_SIZE_CONTENT);   /// 41
lv_obj_set_x( ui_TextArea1, 55 );
lv_obj_set_y( ui_TextArea1, 0 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
if ("1,2,3,4,5,6,7,8,9,0"=="") lv_textarea_set_accepted_chars(ui_TextArea1, NULL);
else lv_textarea_set_accepted_chars(ui_TextArea1, "1,2,3,4,5,6,7,8,9,0");
lv_textarea_set_max_length(ui_TextArea1,3);
lv_textarea_set_one_line(ui_TextArea1,true);
lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_TempHP = lv_label_create(ui_TempHPPanel);
lv_obj_set_width( ui_TempHP, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempHP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempHP, -82 );
lv_obj_set_y( ui_TempHP, 3 );
lv_obj_set_align( ui_TempHP, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempHP,"Temp HP");
lv_obj_set_style_text_font(ui_TempHP, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainPanel = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_MainPanel, 500);
lv_obj_set_height( ui_MainPanel, 111);
lv_obj_set_x( ui_MainPanel, 60 );
lv_obj_set_y( ui_MainPanel, 100 );
lv_obj_set_align( ui_MainPanel, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_MainPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_MainPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MainPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_backslash = lv_label_create(ui_MainPanel);
lv_obj_set_width( ui_backslash, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backslash, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_backslash, -2 );
lv_obj_set_y( ui_backslash, 1 );
lv_obj_set_align( ui_backslash, LV_ALIGN_CENTER );
lv_label_set_text(ui_backslash,"/");
lv_obj_set_style_text_color(ui_backslash, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_backslash, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_backslash, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MHInput = lv_textarea_create(ui_MainPanel);
lv_obj_set_width( ui_MHInput, 170);
lv_obj_set_height( ui_MHInput, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_MHInput, 120 );
lv_obj_set_y( ui_MHInput, 0 );
lv_obj_set_align( ui_MHInput, LV_ALIGN_CENTER );
if ("1,2,3,4,5,6,7,8,9,0"=="") lv_textarea_set_accepted_chars(ui_MHInput, NULL);
else lv_textarea_set_accepted_chars(ui_MHInput, "1,2,3,4,5,6,7,8,9,0");
lv_textarea_set_max_length(ui_MHInput,3);
lv_textarea_set_one_line(ui_MHInput,true);
lv_obj_set_style_text_align(ui_MHInput, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MHInput, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MHInput, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MHInput, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MHInput, 2, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_align(ui_MHInput, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_CHInput = lv_textarea_create(ui_MainPanel);
lv_obj_set_width( ui_CHInput, 170);
lv_obj_set_height( ui_CHInput, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_CHInput, -120 );
lv_obj_set_y( ui_CHInput, 0 );
lv_obj_set_align( ui_CHInput, LV_ALIGN_CENTER );
if ("1,2,3,4,5,6,7,8,9,0"=="") lv_textarea_set_accepted_chars(ui_CHInput, NULL);
else lv_textarea_set_accepted_chars(ui_CHInput, "1,2,3,4,5,6,7,8,9,0");
lv_textarea_set_max_length(ui_CHInput,3);
lv_textarea_set_one_line(ui_CHInput,true);
lv_obj_set_style_text_align(ui_CHInput, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CHInput, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CHInput, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CHInput, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CHInput, 2, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_align(ui_CHInput, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_Settings = lv_button_create(ui_MainScreen);
lv_obj_set_width( ui_Settings, 50);
lv_obj_set_height( ui_Settings, 50);
lv_obj_set_x( ui_Settings, -300 );
lv_obj_set_y( ui_Settings, -170 );
lv_obj_set_align( ui_Settings, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x575252), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Gear = lv_image_create(ui_Settings);
lv_image_set_src(ui_Gear, &ui_img_278415715);
lv_obj_set_width( ui_Gear, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Gear, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Gear, 220 );
lv_obj_set_y( ui_Gear, 221 );
lv_obj_set_align( ui_Gear, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Gear, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Gear, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Gear,230);
lv_obj_set_style_image_recolor(ui_Gear, lv_color_hex(0xF2E8E8), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_image_recolor_opa(ui_Gear, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_min_width(ui_Gear, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_max_width(ui_Gear, 480, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_min_height(ui_Gear, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_max_height(ui_Gear, 480, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_Gear, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back = lv_button_create(ui_MainScreen);
lv_obj_set_width( ui_Back, 50);
lv_obj_set_height( ui_Back, 50);
lv_obj_set_x( ui_Back, -360 );
lv_obj_set_y( ui_Back, -170 );
lv_obj_set_align( ui_Back, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Back, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Back, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Back, lv_color_hex(0xF64031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Back, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arrow = lv_image_create(ui_Back);
lv_image_set_src(ui_arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_arrow, 220 );
lv_obj_set_y( ui_arrow, 221 );
lv_obj_set_align( ui_arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_arrow,230);
lv_obj_set_style_image_recolor(ui_arrow, lv_color_hex(0xF2E8E8), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_image_recolor_opa(ui_arrow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_min_width(ui_arrow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_max_width(ui_arrow, 480, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_min_height(ui_arrow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_max_height(ui_arrow, 480, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_arrow, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NamePanel = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_NamePanel, 501);
lv_obj_set_height( ui_NamePanel, 58);
lv_obj_set_x( ui_NamePanel, 48 );
lv_obj_set_y( ui_NamePanel, -170 );
lv_obj_set_align( ui_NamePanel, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_NamePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_NamePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_NamePanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_NamePanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_NamePanel, lv_color_hex(0x2A2727), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_NamePanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_NamePanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_NamePanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_NamePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_NamePanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CharName = lv_textarea_create(ui_NamePanel);
lv_obj_set_width( ui_CharName, 491);
lv_obj_set_height( ui_CharName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CharName, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_CharName,"Character Name");
lv_textarea_set_placeholder_text(ui_CharName,"Placeholder...");
lv_textarea_set_one_line(ui_CharName,true);
lv_obj_set_style_text_align(ui_CharName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CharName, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_CharName, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_HealDamageContainer = lv_obj_create(ui_WholeScreen);
lv_obj_remove_style_all(ui_HealDamageContainer);
lv_obj_set_width( ui_HealDamageContainer, 600);
lv_obj_set_height( ui_HealDamageContainer, 318);
lv_obj_set_x( ui_HealDamageContainer, -120 );
lv_obj_set_y( ui_HealDamageContainer, -60 );
lv_obj_set_align( ui_HealDamageContainer, LV_ALIGN_BOTTOM_MID );
lv_obj_remove_flag( ui_HealDamageContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DamageButton = lv_button_create(ui_HealDamageContainer);
lv_obj_set_width( ui_DamageButton, 150);
lv_obj_set_height( ui_DamageButton, 50);
lv_obj_set_x( ui_DamageButton, -183 );
lv_obj_set_y( ui_DamageButton, 110 );
lv_obj_set_align( ui_DamageButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DamageButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_DamageButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DamageButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DamageButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_DamageButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_DamageButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_DamageButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DamageButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Damage = lv_label_create(ui_DamageButton);
lv_obj_set_width( ui_Damage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Damage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Damage, LV_ALIGN_CENTER );
lv_label_set_text(ui_Damage,"Damage");
lv_obj_set_style_text_color(ui_Damage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Damage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Damage, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HealButton = lv_button_create(ui_HealDamageContainer);
lv_obj_set_width( ui_HealButton, 150);
lv_obj_set_height( ui_HealButton, 50);
lv_obj_set_x( ui_HealButton, -180 );
lv_obj_set_y( ui_HealButton, -30 );
lv_obj_set_align( ui_HealButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HealButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_HealButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HealButton, lv_color_hex(0x66A5ED), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HealButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_HealButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HealButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Heal = lv_label_create(ui_HealButton);
lv_obj_set_width( ui_Heal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Heal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Heal, LV_ALIGN_CENTER );
lv_label_set_text(ui_Heal,"Heal");
lv_obj_set_style_text_color(ui_Heal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Heal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Heal, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InputArea = lv_textarea_create(ui_HealDamageContainer);
lv_obj_set_width( ui_InputArea, 120);
lv_obj_set_height( ui_InputArea, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_InputArea, -180 );
lv_obj_set_y( ui_InputArea, 40 );
lv_obj_set_align( ui_InputArea, LV_ALIGN_CENTER );
if ("1,2,3,4,5,6,7,8,9,0"=="") lv_textarea_set_accepted_chars(ui_InputArea, NULL);
else lv_textarea_set_accepted_chars(ui_InputArea, "1,2,3,4,5,6,7,8,9,0");
lv_textarea_set_max_length(ui_InputArea,3);
lv_textarea_set_one_line(ui_InputArea,true);
lv_obj_set_style_text_align(ui_InputArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InputArea, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InputArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InputArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_InputArea, 2, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_align(ui_InputArea, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_MaxHealthSubScreen = lv_obj_create(ui_Health_Screen);
lv_obj_remove_style_all(ui_MaxHealthSubScreen);
lv_obj_set_width( ui_MaxHealthSubScreen, 780);
lv_obj_set_height( ui_MaxHealthSubScreen, 459);
lv_obj_set_x( ui_MaxHealthSubScreen, -5 );
lv_obj_set_y( ui_MaxHealthSubScreen, 0 );
lv_obj_set_align( ui_MaxHealthSubScreen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MaxHealthSubScreen, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_MaxHealthSubScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MHPad = ui_NumPad_create(ui_MaxHealthSubScreen);
lv_keyboard_set_mode(ui_MHPad,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_MHPad, 780);
lv_obj_set_height( ui_MHPad, 350);
lv_obj_set_x( ui_MHPad, 0 );
lv_obj_set_y( ui_MHPad, 40 );
lv_obj_set_align( ui_MHPad, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_MHPad, LV_OBJ_FLAG_HIDDEN );    /// Flags

ui_MHInputDisplay = lv_textarea_create(ui_MaxHealthSubScreen);
lv_obj_set_width( ui_MHInputDisplay, 500);
lv_obj_set_height( ui_MHInputDisplay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MHInputDisplay, 0 );
lv_obj_set_y( ui_MHInputDisplay, -180 );
lv_obj_set_align( ui_MHInputDisplay, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_MHInputDisplay,3);
lv_textarea_set_placeholder_text(ui_MHInputDisplay,"Max Health...");
lv_textarea_set_one_line(ui_MHInputDisplay,true);
lv_obj_set_style_text_color(ui_MHInputDisplay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MHInputDisplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MHInputDisplay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MHInputDisplay, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_color(ui_MHInputDisplay, lv_color_hex(0x8B7F7F), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MHInputDisplay, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MHInputDisplay, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_CurrentHealthSubScreen = lv_obj_create(ui_Health_Screen);
lv_obj_remove_style_all(ui_CurrentHealthSubScreen);
lv_obj_set_width( ui_CurrentHealthSubScreen, 780);
lv_obj_set_height( ui_CurrentHealthSubScreen, 462);
lv_obj_set_x( ui_CurrentHealthSubScreen, 0 );
lv_obj_set_y( ui_CurrentHealthSubScreen, 4 );
lv_obj_set_align( ui_CurrentHealthSubScreen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CurrentHealthSubScreen, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_CurrentHealthSubScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CHPad = ui_NumPad_create(ui_CurrentHealthSubScreen);
lv_keyboard_set_mode(ui_CHPad,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_CHPad, 780);
lv_obj_set_height( ui_CHPad, 350);
lv_obj_set_x( ui_CHPad, 0 );
lv_obj_set_y( ui_CHPad, 40 );
lv_obj_set_align( ui_CHPad, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_CHPad, LV_OBJ_FLAG_HIDDEN );    /// Flags

ui_CHInputDisplay = lv_textarea_create(ui_CurrentHealthSubScreen);
lv_obj_set_width( ui_CHInputDisplay, 500);
lv_obj_set_height( ui_CHInputDisplay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CHInputDisplay, 0 );
lv_obj_set_y( ui_CHInputDisplay, -180 );
lv_obj_set_align( ui_CHInputDisplay, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_CHInputDisplay,3);
lv_textarea_set_placeholder_text(ui_CHInputDisplay,"Current Health...");
lv_textarea_set_one_line(ui_CHInputDisplay,true);
lv_obj_set_style_text_color(ui_CHInputDisplay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CHInputDisplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CHInputDisplay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CHInputDisplay, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_color(ui_CHInputDisplay, lv_color_hex(0x8B7F7F), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CHInputDisplay, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CHInputDisplay, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_TempSubScreen = lv_obj_create(ui_Health_Screen);
lv_obj_remove_style_all(ui_TempSubScreen);
lv_obj_set_width( ui_TempSubScreen, 781);
lv_obj_set_height( ui_TempSubScreen, 470);
lv_obj_set_align( ui_TempSubScreen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TempSubScreen, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_TempSubScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempPad = ui_NumPad_create(ui_TempSubScreen);
lv_keyboard_set_mode(ui_TempPad,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_TempPad, 780);
lv_obj_set_height( ui_TempPad, 350);
lv_obj_set_x( ui_TempPad, 0 );
lv_obj_set_y( ui_TempPad, 40 );
lv_obj_set_align( ui_TempPad, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TempPad, LV_OBJ_FLAG_HIDDEN );    /// Flags

ui_TempInputDisplay = lv_textarea_create(ui_TempSubScreen);
lv_obj_set_width( ui_TempInputDisplay, 500);
lv_obj_set_height( ui_TempInputDisplay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempInputDisplay, 0 );
lv_obj_set_y( ui_TempInputDisplay, -180 );
lv_obj_set_align( ui_TempInputDisplay, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_TempInputDisplay,3);
lv_textarea_set_placeholder_text(ui_TempInputDisplay,"Temp Health...");
lv_textarea_set_one_line(ui_TempInputDisplay,true);
lv_obj_set_style_text_color(ui_TempInputDisplay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempInputDisplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TempInputDisplay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempInputDisplay, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_color(ui_TempInputDisplay, lv_color_hex(0x8B7F7F), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempInputDisplay, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TempInputDisplay, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_NameSubScreen = lv_obj_create(ui_Health_Screen);
lv_obj_remove_style_all(ui_NameSubScreen);
lv_obj_set_width( ui_NameSubScreen, 792);
lv_obj_set_height( ui_NameSubScreen, 476);
lv_obj_set_x( ui_NameSubScreen, -2 );
lv_obj_set_y( ui_NameSubScreen, -1 );
lv_obj_set_align( ui_NameSubScreen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_NameSubScreen, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_NameSubScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_NameBoard = ui_NumPad_create(ui_NameSubScreen);
lv_keyboard_set_mode(ui_NameBoard,LV_KEYBOARD_MODE_TEXT_LOWER);
lv_obj_set_width( ui_NameBoard, 772);
lv_obj_set_height( ui_NameBoard, 345);
lv_obj_set_x( ui_NameBoard, 0 );
lv_obj_set_y( ui_NameBoard, 50 );
lv_obj_set_align( ui_NameBoard, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_NameBoard, LV_OBJ_FLAG_HIDDEN );    /// Flags

ui_NameBoardDisplay = lv_textarea_create(ui_NameSubScreen);
lv_obj_set_width( ui_NameBoardDisplay, 642);
lv_obj_set_height( ui_NameBoardDisplay, LV_SIZE_CONTENT);   /// 66
lv_obj_set_x( ui_NameBoardDisplay, 55 );
lv_obj_set_y( ui_NameBoardDisplay, -180 );
lv_obj_set_align( ui_NameBoardDisplay, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_NameBoardDisplay,50);
lv_textarea_set_placeholder_text(ui_NameBoardDisplay,"Name...");
lv_textarea_set_one_line(ui_NameBoardDisplay,true);
lv_obj_set_style_text_color(ui_NameBoardDisplay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NameBoardDisplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_NameBoardDisplay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NameBoardDisplay, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_color(ui_NameBoardDisplay, lv_color_hex(0x8B7F7F), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NameBoardDisplay, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_NameBoardDisplay, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_XButton = lv_button_create(ui_Health_Screen);
lv_obj_set_width( ui_XButton, 56);
lv_obj_set_height( ui_XButton, 46);
lv_obj_set_x( ui_XButton, -330 );
lv_obj_set_y( ui_XButton, -180 );
lv_obj_set_align( ui_XButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_XButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_XButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_XButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_XButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_xButtonText = lv_label_create(ui_XButton);
lv_obj_set_width( ui_xButtonText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_xButtonText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_xButtonText, LV_ALIGN_CENTER );
lv_label_set_text(ui_xButtonText,"X");
lv_obj_set_style_text_font(ui_xButtonText, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HealDamagePad = ui_NumPad_create(ui_Health_Screen);
lv_keyboard_set_mode(ui_HealDamagePad,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_HealDamagePad, 600);
lv_obj_set_height( ui_HealDamagePad, 450);
lv_obj_set_x( ui_HealDamagePad, 83 );
lv_obj_set_y( ui_HealDamagePad, -1 );
lv_obj_add_flag( ui_HealDamagePad, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MHInput, ui_event_MHInput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CHInput, ui_event_CHInput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Back, ui_event_Back, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CharName, ui_event_CharName, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DamageButton, ui_event_DamageButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HealButton, ui_event_HealButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_InputArea, ui_event_InputArea, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_MHPad,ui_MHInputDisplay);
lv_obj_add_event_cb(ui_MHPad, ui_event_MHPad_NumPad, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_CHPad,ui_CHInputDisplay);
lv_obj_add_event_cb(ui_CHPad, ui_event_CHPad_NumPad, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_TempPad,ui_TempInputDisplay);
lv_obj_add_event_cb(ui_TempPad, ui_event_TempPad_NumPad, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_NameBoard,ui_NameBoardDisplay);
lv_obj_add_event_cb(ui_NameBoard, ui_event_NameBoard_NumPad, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_XButton, ui_event_XButton, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_HealDamagePad,ui_InputArea);
lv_obj_add_event_cb(ui_HealDamagePad, ui_event_HealDamagePad_NumPad, LV_EVENT_ALL, NULL);
uic_Image1 = ui_Gear;
uic_Image1 = ui_arrow;
uic_Heal_Button = ui_HealButton;

}
