// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DND_Screen

#include "../ui.h"

void ui_ProfileChoiceScreen_screen_init(void)
{
ui_ProfileChoiceScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ProfileChoiceScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_ProfileChoiceScreen, &ui_img_wood_paneling_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Container9 = lv_obj_create(ui_ProfileChoiceScreen);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_width( ui_Container9, 600);
lv_obj_set_height( ui_Container9, 440);
lv_obj_set_x( ui_Container9, -1 );
lv_obj_set_y( ui_Container9, 0 );
lv_obj_set_align( ui_Container9, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container9, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown1 = lv_dropdown_create(ui_ProfileChoiceScreen);
lv_dropdown_set_options( ui_Dropdown1, "Option 1\nOption 2\nOption 3" );
lv_obj_set_width( ui_Dropdown1, 400);
lv_obj_set_height( ui_Dropdown1, 50);
lv_obj_set_x( ui_Dropdown1, 0 );
lv_obj_set_y( ui_Dropdown1, 20 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_border_color(ui_Dropdown1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Dropdown1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_ChooseProfile = lv_label_create(ui_ProfileChoiceScreen);
lv_obj_set_width( ui_ChooseProfile, lv_pct(50));
lv_obj_set_height( ui_ChooseProfile, lv_pct(20));
lv_obj_set_x( ui_ChooseProfile, 0 );
lv_obj_set_y( ui_ChooseProfile, -120 );
lv_obj_set_align( ui_ChooseProfile, LV_ALIGN_CENTER );
lv_label_set_text(ui_ChooseProfile,"Choose Your Profile");
lv_obj_set_style_text_align(ui_ChooseProfile, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ChooseProfile, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_button_create(ui_ProfileChoiceScreen);
lv_obj_set_width( ui_Button3, 180);
lv_obj_set_height( ui_Button3, 50);
lv_obj_set_x( ui_Button3, 160 );
lv_obj_set_y( ui_Button3, 120 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AcceptProfile = lv_label_create(ui_Button3);
lv_obj_set_width( ui_AcceptProfile, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AcceptProfile, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AcceptProfile, LV_ALIGN_CENTER );
lv_label_set_text(ui_AcceptProfile,"Confirm");
lv_obj_set_style_text_font(ui_AcceptProfile, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackProfile = lv_button_create(ui_ProfileChoiceScreen);
lv_obj_set_width( ui_BackProfile, 180);
lv_obj_set_height( ui_BackProfile, 50);
lv_obj_set_x( ui_BackProfile, -160 );
lv_obj_set_y( ui_BackProfile, 120 );
lv_obj_set_align( ui_BackProfile, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackProfile, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BackProfile, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BackProfile, lv_color_hex(0xC72929), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BackProfile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_BackProfile);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Back");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackProfile, ui_event_BackProfile, LV_EVENT_ALL, NULL);

}
