// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DND_Screen

#include "../ui.h"

void ui_SettingScreen_screen_init(void)
{
ui_SettingScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AllSettingsContainer = lv_obj_create(ui_SettingScreen);
lv_obj_remove_style_all(ui_AllSettingsContainer);
lv_obj_set_width( ui_AllSettingsContainer, 769);
lv_obj_set_height( ui_AllSettingsContainer, 468);
lv_obj_set_x( ui_AllSettingsContainer, 1 );
lv_obj_set_y( ui_AllSettingsContainer, 0 );
lv_obj_set_align( ui_AllSettingsContainer, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_AllSettingsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HPColor = lv_obj_create(ui_AllSettingsContainer);
lv_obj_remove_style_all(ui_HPColor);
lv_obj_set_width( ui_HPColor, 442);
lv_obj_set_height( ui_HPColor, 159);
lv_obj_set_x( ui_HPColor, -10 );
lv_obj_set_y( ui_HPColor, -60 );
lv_obj_set_align( ui_HPColor, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_HPColor, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HPColorChoice = lv_dropdown_create(ui_HPColor);
lv_dropdown_set_options( ui_HPColorChoice, "Red\nBlue\nGreen\nPurple\nYellow\nOrange" );
lv_obj_set_width( ui_HPColorChoice, 190);
lv_obj_set_height( ui_HPColorChoice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HPColorChoice, 120 );
lv_obj_set_y( ui_HPColorChoice, -10 );
lv_obj_set_align( ui_HPColorChoice, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HPColorChoice, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_border_color(ui_HPColorChoice, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HPColorChoice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_HPLabel = lv_label_create(ui_HPColor);
lv_obj_set_width( ui_HPLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HPLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HPLabel, 120 );
lv_obj_set_y( ui_HPLabel, -70 );
lv_obj_set_align( ui_HPLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HPLabel,"HitPoint Color");
lv_obj_set_style_text_font(ui_HPLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempHPColor = lv_obj_create(ui_AllSettingsContainer);
lv_obj_remove_style_all(ui_TempHPColor);
lv_obj_set_width( ui_TempHPColor, 455);
lv_obj_set_height( ui_TempHPColor, 242);
lv_obj_set_x( ui_TempHPColor, -10 );
lv_obj_set_y( ui_TempHPColor, 30 );
lv_obj_set_align( ui_TempHPColor, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TempHPColor, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_THPColorChoice = lv_dropdown_create(ui_TempHPColor);
lv_dropdown_set_options( ui_THPColorChoice, "Blue\nRed\nGreen\nPurple\nYellow\nOrange" );
lv_obj_set_width( ui_THPColorChoice, 190);
lv_obj_set_height( ui_THPColorChoice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_THPColorChoice, 120 );
lv_obj_set_y( ui_THPColorChoice, 80 );
lv_obj_set_align( ui_THPColorChoice, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_THPColorChoice, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_border_color(ui_THPColorChoice, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_THPColorChoice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_THPLabel = lv_label_create(ui_TempHPColor);
lv_obj_set_width( ui_THPLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_THPLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_THPLabel, 120 );
lv_obj_set_y( ui_THPLabel, 20 );
lv_obj_set_align( ui_THPLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_THPLabel,"Temp Hit Point Color");
lv_obj_set_style_text_font(ui_THPLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DeleteButton1 = lv_button_create(ui_AllSettingsContainer);
lv_obj_set_width( ui_DeleteButton1, 181);
lv_obj_set_height( ui_DeleteButton1, 50);
lv_obj_set_x( ui_DeleteButton1, -240 );
lv_obj_set_y( ui_DeleteButton1, 190 );
lv_obj_set_align( ui_DeleteButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DeleteButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_DeleteButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DeleteButton1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DeleteButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label17 = lv_label_create(ui_DeleteButton1);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"DELETE CHARACTER");

ui_PlayerInfo = lv_obj_create(ui_AllSettingsContainer);
lv_obj_set_width( ui_PlayerInfo, 250);
lv_obj_set_height( ui_PlayerInfo, 300);
lv_obj_set_x( ui_PlayerInfo, -240 );
lv_obj_set_y( ui_PlayerInfo, 0 );
lv_obj_set_align( ui_PlayerInfo, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PlayerInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PlayerInfo, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PlayerInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_PlayerInfo);
lv_obj_set_width( ui_Panel4, 170);
lv_obj_set_height( ui_Panel4, 60);
lv_obj_set_x( ui_Panel4, 0 );
lv_obj_set_y( ui_Panel4, -80 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_currentProfile = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_currentProfile, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentProfile, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentProfile, 0 );
lv_obj_set_y( ui_currentProfile, -12 );
lv_obj_set_align( ui_currentProfile, LV_ALIGN_CENTER );
lv_label_set_text(ui_currentProfile,"Current Profile");
lv_obj_set_style_text_font(ui_currentProfile, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CPText = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_CPText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CPText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CPText, 0 );
lv_obj_set_y( ui_CPText, 14 );
lv_obj_set_align( ui_CPText, LV_ALIGN_CENTER );
lv_label_set_text(ui_CPText,"Text");
lv_obj_set_style_text_color(ui_CPText, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CPText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_PlayerInfo);
lv_obj_set_width( ui_Panel5, 210);
lv_obj_set_height( ui_Panel5, 70);
lv_obj_set_x( ui_Panel5, 0 );
lv_obj_set_y( ui_Panel5, 40 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CurrentCharacter = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_CurrentCharacter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CurrentCharacter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CurrentCharacter, 0 );
lv_obj_set_y( ui_CurrentCharacter, -11 );
lv_obj_set_align( ui_CurrentCharacter, LV_ALIGN_CENTER );
lv_label_set_text(ui_CurrentCharacter,"Current Character");
lv_obj_set_style_text_font(ui_CurrentCharacter, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CCText = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_CCText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CCText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CCText, 0 );
lv_obj_set_y( ui_CCText, 18 );
lv_obj_set_align( ui_CCText, LV_ALIGN_CENTER );
lv_label_set_text(ui_CCText,"text");
lv_obj_set_style_text_color(ui_CCText, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CCText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back2 = lv_button_create(ui_AllSettingsContainer);
lv_obj_set_width( ui_Back2, 50);
lv_obj_set_height( ui_Back2, 50);
lv_obj_set_x( ui_Back2, -360 );
lv_obj_set_y( ui_Back2, -200 );
lv_obj_set_align( ui_Back2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Back2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Back2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Back2, lv_color_hex(0xF64031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Back2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arrow1 = lv_image_create(ui_Back2);
lv_image_set_src(ui_arrow1, &ui_img_arrow_png);
lv_obj_set_width( ui_arrow1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_arrow1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_arrow1, 220 );
lv_obj_set_y( ui_arrow1, 221 );
lv_obj_set_align( ui_arrow1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_arrow1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_arrow1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_arrow1,230);
lv_obj_set_style_image_recolor(ui_arrow1, lv_color_hex(0xF2E8E8), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_image_recolor_opa(ui_arrow1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_min_width(ui_arrow1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_max_width(ui_arrow1, 480, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_min_height(ui_arrow1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_max_height(ui_arrow1, 480, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_arrow1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ConfirmDeleteContainer = lv_obj_create(ui_SettingScreen);
lv_obj_remove_style_all(ui_ConfirmDeleteContainer);
lv_obj_set_width( ui_ConfirmDeleteContainer, 474);
lv_obj_set_height( ui_ConfirmDeleteContainer, 241);
lv_obj_set_align( ui_ConfirmDeleteContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ConfirmDeleteContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_ConfirmDeleteContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label20 = lv_label_create(ui_ConfirmDeleteContainer);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, 0 );
lv_obj_set_y( ui_Label20, -60 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"ARE YOU SURE YOU WANT TO\n   DELETE THIS CHARACTER");

ui_Button13 = lv_button_create(ui_ConfirmDeleteContainer);
lv_obj_set_width( ui_Button13, 100);
lv_obj_set_height( ui_Button13, 50);
lv_obj_set_x( ui_Button13, -100 );
lv_obj_set_y( ui_Button13, 30 );
lv_obj_set_align( ui_Button13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_Button13);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"YES");

ui_Button14 = lv_button_create(ui_ConfirmDeleteContainer);
lv_obj_set_width( ui_Button14, 100);
lv_obj_set_height( ui_Button14, 50);
lv_obj_set_x( ui_Button14, 100 );
lv_obj_set_y( ui_Button14, 30 );
lv_obj_set_align( ui_Button14, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label22 = lv_label_create(ui_Button14);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"NO");

lv_obj_add_event_cb(ui_DeleteButton1, ui_event_DeleteButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Back2, ui_event_Back2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
uic_Image1 = ui_arrow1;

}
