// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DND_Screen

#include "../ui.h"

void ui_WelcomeScreen_screen_init(void)
{
ui_WelcomeScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_WelcomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_WelcomeScreen, &ui_img_wood_paneling_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_GuestChoice = lv_button_create(ui_WelcomeScreen);
lv_obj_set_width( ui_GuestChoice, 300);
lv_obj_set_height( ui_GuestChoice, 80);
lv_obj_set_x( ui_GuestChoice, 0 );
lv_obj_set_y( ui_GuestChoice, 120 );
lv_obj_set_align( ui_GuestChoice, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_GuestChoice, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_GuestChoice, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_shadow_color(ui_GuestChoice, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_GuestChoice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_GuestChoice, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_GuestChoice, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Guest = lv_label_create(ui_GuestChoice);
lv_obj_set_width( ui_Guest, lv_pct(80));
lv_obj_set_height( ui_Guest, lv_pct(80));
lv_obj_set_x( ui_Guest, 0 );
lv_obj_set_y( ui_Guest, 6 );
lv_obj_set_align( ui_Guest, LV_ALIGN_CENTER );
lv_label_set_text(ui_Guest,"Guest");
lv_obj_set_style_text_align(ui_Guest, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Guest, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_min_width(ui_Guest, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_max_width(ui_Guest, 8192, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_min_height(ui_Guest, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_max_height(ui_Guest, 8192, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_rotation(ui_Guest, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_Guest, 256, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CharacterChoice = lv_button_create(ui_WelcomeScreen);
lv_obj_set_width( ui_CharacterChoice, 300);
lv_obj_set_height( ui_CharacterChoice, 80);
lv_obj_set_align( ui_CharacterChoice, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CharacterChoice, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_CharacterChoice, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_shadow_color(ui_CharacterChoice, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_CharacterChoice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_CharacterChoice, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_CharacterChoice, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Choose_Profile = lv_label_create(ui_CharacterChoice);
lv_obj_set_width( ui_Choose_Profile, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Choose_Profile, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Choose_Profile, LV_ALIGN_CENTER );
lv_label_set_text(ui_Choose_Profile,"Choose Profile");
lv_obj_set_style_text_align(ui_Choose_Profile, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Choose_Profile, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Welcome = lv_label_create(ui_WelcomeScreen);
lv_obj_set_width( ui_Welcome, 625);
lv_obj_set_height( ui_Welcome, 100);
lv_obj_set_x( ui_Welcome, 0 );
lv_obj_set_y( ui_Welcome, -136 );
lv_obj_set_align( ui_Welcome, LV_ALIGN_CENTER );
lv_label_set_text(ui_Welcome,"Welcome to DnD OS");
lv_obj_set_style_text_color(ui_Welcome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Welcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Welcome, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Welcome, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Welcome, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Welcome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Welcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Welcome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Welcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Welcome, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Welcome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Welcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Welcome, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Welcome, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Welcome, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Welcome, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Welcome, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Welcome, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_GuestChoice, ui_event_GuestChoice, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CharacterChoice, ui_event_CharacterChoice, LV_EVENT_ALL, NULL);

}
