// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DND_Screen

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_WelcomeScreen
void ui_WelcomeScreen_screen_init(void);
lv_obj_t *ui_WelcomeScreen;
void ui_event_GuestChoice( lv_event_t * e);
lv_obj_t *ui_GuestChoice;
lv_obj_t *ui_Guest;
void ui_event_CharacterChoice( lv_event_t * e);
lv_obj_t *ui_CharacterChoice;
lv_obj_t *ui_Choose_Profile;
lv_obj_t *ui_Welcome;
// CUSTOM VARIABLES


// SCREEN: ui_ProfileChoiceScreen
void ui_ProfileChoiceScreen_screen_init(void);
lv_obj_t *ui_ProfileChoiceScreen;
lv_obj_t *ui_Container9;
lv_obj_t *ui_Dropdown1;
lv_obj_t *ui_ChooseProfile;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_AcceptProfile;
void ui_event_BackProfile( lv_event_t * e);
lv_obj_t *ui_BackProfile;
lv_obj_t *ui_Label8;
// CUSTOM VARIABLES


// SCREEN: ui_CharChoiceScreen
void ui_CharChoiceScreen_screen_init(void);
lv_obj_t *ui_CharChoiceScreen;
lv_obj_t *ui_Container10;
lv_obj_t *ui_Dropdown2;
lv_obj_t *ui_ChooseCharacter;
void ui_event_BackChar( lv_event_t * e);
lv_obj_t *ui_BackChar;
lv_obj_t *ui_Label9;
void ui_event_Button6( lv_event_t * e);
lv_obj_t *ui_Button6;
lv_obj_t *ui_AcceptChar;
void ui_event_Settings1( lv_event_t * e);
lv_obj_t *ui_Settings1;
lv_obj_t *ui_Gear1;
// CUSTOM VARIABLES
lv_obj_t *uic_Image1;


// SCREEN: ui_Health_Screen
void ui_Health_Screen_screen_init(void);
lv_obj_t *ui_Health_Screen;
lv_obj_t *ui_WholeScreen;
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_TempHPPanel;
void ui_event_TextArea1( lv_event_t * e);
lv_obj_t *ui_TextArea1;
lv_obj_t *ui_TempHP;
lv_obj_t *ui_MainPanel;
lv_obj_t *ui_backslash;
void ui_event_MHInput( lv_event_t * e);
lv_obj_t *ui_MHInput;
void ui_event_CHInput( lv_event_t * e);
lv_obj_t *ui_CHInput;
void ui_event_Settings( lv_event_t * e);
lv_obj_t *ui_Settings;
lv_obj_t *ui_Gear;
void ui_event_Back( lv_event_t * e);
lv_obj_t *ui_Back;
lv_obj_t *ui_arrow;
lv_obj_t *ui_NamePanel;
void ui_event_CharName( lv_event_t * e);
lv_obj_t *ui_CharName;
lv_obj_t *ui_HealDamageContainer;
void ui_event_DamageButton( lv_event_t * e);
lv_obj_t *ui_DamageButton;
lv_obj_t *ui_Damage;
void ui_event_HealButton( lv_event_t * e);
lv_obj_t *ui_HealButton;
lv_obj_t *ui_Heal;
void ui_event_InputArea( lv_event_t * e);
lv_obj_t *ui_InputArea;
lv_obj_t *ui_MaxHealthSubScreen;
void ui_event_MHPad_NumPad( lv_event_t * e);
lv_obj_t *ui_MHPad;
lv_obj_t *ui_MHInputDisplay;
lv_obj_t *ui_CurrentHealthSubScreen;
void ui_event_CHPad_NumPad( lv_event_t * e);
lv_obj_t *ui_CHPad;
lv_obj_t *ui_CHInputDisplay;
lv_obj_t *ui_TempSubScreen;
void ui_event_TempPad_NumPad( lv_event_t * e);
lv_obj_t *ui_TempPad;
lv_obj_t *ui_TempInputDisplay;
lv_obj_t *ui_NameSubScreen;
void ui_event_NameBoard_NumPad( lv_event_t * e);
lv_obj_t *ui_NameBoard;
lv_obj_t *ui_NameBoardDisplay;
void ui_event_XButton( lv_event_t * e);
lv_obj_t *ui_XButton;
lv_obj_t *ui_xButtonText;
void ui_event_HealDamagePad_NumPad( lv_event_t * e);
lv_obj_t *ui_HealDamagePad;
// CUSTOM VARIABLES
lv_obj_t *uic_Image1;
lv_obj_t *uic_Image1;
lv_obj_t *uic_Heal_Button;


// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
lv_obj_t *ui_SettingScreen;
lv_obj_t *ui_AllSettingsContainer;
lv_obj_t *ui_HPColor;
lv_obj_t *ui_HPColorChoice;
lv_obj_t *ui_HPLabel;
lv_obj_t *ui_TempHPColor;
lv_obj_t *ui_THPColorChoice;
lv_obj_t *ui_THPLabel;
void ui_event_DeleteButton1( lv_event_t * e);
lv_obj_t *ui_DeleteButton1;
lv_obj_t *ui_Label17;
lv_obj_t *ui_PlayerInfo;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_currentProfile;
lv_obj_t *ui_CPText;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_CurrentCharacter;
lv_obj_t *ui_CCText;
void ui_event_Back2( lv_event_t * e);
lv_obj_t *ui_Back2;
lv_obj_t *ui_arrow1;
lv_obj_t *ui_ConfirmDeleteContainer;
lv_obj_t *ui_Label20;
void ui_event_Button13( lv_event_t * e);
lv_obj_t *ui_Button13;
lv_obj_t *ui_Label21;
void ui_event_Button14( lv_event_t * e);
lv_obj_t *ui_Button14;
lv_obj_t *ui_Label22;
// CUSTOM VARIABLES
lv_obj_t *uic_Image1;

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_GuestChoice( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Health_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Health_Screen_screen_init);
}
}

void ui_event_CharacterChoice( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ProfileChoiceScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_ProfileChoiceScreen_screen_init);
}
}

void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_CharChoiceScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_CharChoiceScreen_screen_init);
}
}

void ui_event_BackProfile( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_WelcomeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_WelcomeScreen_screen_init);
}
}

void ui_event_BackChar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ProfileChoiceScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_ProfileChoiceScreen_screen_init);
}
}

void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Health_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Health_Screen_screen_init);
}
}

void ui_event_Settings1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Health_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Health_Screen_screen_init);
}
}

void ui_event_TextArea1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_WholeScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_TempSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_MHInput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_WholeScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_MaxHealthSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_CHInput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_WholeScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_CurrentHealthSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_Settings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SettingScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_SettingScreen_screen_init);
}
}

void ui_event_Back( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_CharChoiceScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_CharChoiceScreen_screen_init);
}
}

void ui_event_CharName( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_WholeScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_NameSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_DamageButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_MainScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_HealDamagePad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_HealButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_MainScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_HealDamagePad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_InputArea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_HealDamagePad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_MainScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_MHPad_NumPad( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_WholeScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_MaxHealthSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_CHPad_NumPad( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_CurrentHealthSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_WholeScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_TempPad_NumPad( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_WholeScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_TempSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_NameBoard_NumPad( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_NameSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_WholeScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_XButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_MaxHealthSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_CurrentHealthSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_WholeScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_HealDamagePad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_MainScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_TempSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_NameSubScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_HealDamagePad_NumPad( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_MainScreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_XButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_HealDamagePad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_DeleteButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_AllSettingsContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_ConfirmDeleteContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_Back2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Health_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Health_Screen_screen_init);
}
}

void ui_event_Button13( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_CharChoiceScreen, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_CharChoiceScreen_screen_init);
}
}

void ui_event_Button14( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_ConfirmDeleteContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_AllSettingsContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_WelcomeScreen_screen_init();
ui_ProfileChoiceScreen_screen_init();
ui_CharChoiceScreen_screen_init();
ui_Health_Screen_screen_init();
ui_SettingScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_WelcomeScreen);
}
