// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DND_Screen

#ifndef _DND_SCREEN_UI_H
#define _DND_SCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_WelcomeScreen
void ui_WelcomeScreen_screen_init(void);
extern lv_obj_t *ui_WelcomeScreen;
void ui_event_GuestChoice( lv_event_t * e);
extern lv_obj_t *ui_GuestChoice;
extern lv_obj_t *ui_Guest;
void ui_event_CharacterChoice( lv_event_t * e);
extern lv_obj_t *ui_CharacterChoice;
extern lv_obj_t *ui_Choose_Profile;
extern lv_obj_t *ui_Welcome;
// CUSTOM VARIABLES

// SCREEN: ui_ProfileChoiceScreen
void ui_ProfileChoiceScreen_screen_init(void);
extern lv_obj_t *ui_ProfileChoiceScreen;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_Dropdown1;
extern lv_obj_t *ui_ChooseProfile;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_AcceptProfile;
void ui_event_BackProfile( lv_event_t * e);
extern lv_obj_t *ui_BackProfile;
extern lv_obj_t *ui_Label8;
// CUSTOM VARIABLES

// SCREEN: ui_CharChoiceScreen
void ui_CharChoiceScreen_screen_init(void);
extern lv_obj_t *ui_CharChoiceScreen;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_Dropdown2;
extern lv_obj_t *ui_ChooseCharacter;
void ui_event_BackChar( lv_event_t * e);
extern lv_obj_t *ui_BackChar;
extern lv_obj_t *ui_Label9;
void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_AcceptChar;
void ui_event_Settings1( lv_event_t * e);
extern lv_obj_t *ui_Settings1;
extern lv_obj_t *ui_Gear1;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Image1;

// SCREEN: ui_Health_Screen
void ui_Health_Screen_screen_init(void);
extern lv_obj_t *ui_Health_Screen;
extern lv_obj_t *ui_WholeScreen;
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_TempHPPanel;
void ui_event_TextArea1( lv_event_t * e);
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_TempHP;
extern lv_obj_t *ui_MainPanel;
extern lv_obj_t *ui_backslash;
void ui_event_MHInput( lv_event_t * e);
extern lv_obj_t *ui_MHInput;
void ui_event_CHInput( lv_event_t * e);
extern lv_obj_t *ui_CHInput;
void ui_event_Settings( lv_event_t * e);
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_Gear;
void ui_event_Back( lv_event_t * e);
extern lv_obj_t *ui_Back;
extern lv_obj_t *ui_arrow;
extern lv_obj_t *ui_NamePanel;
void ui_event_CharName( lv_event_t * e);
extern lv_obj_t *ui_CharName;
extern lv_obj_t *ui_HealDamageContainer;
void ui_event_DamageButton( lv_event_t * e);
extern lv_obj_t *ui_DamageButton;
extern lv_obj_t *ui_Damage;
void ui_event_HealButton( lv_event_t * e);
extern lv_obj_t *ui_HealButton;
extern lv_obj_t *ui_Heal;
void ui_event_InputArea( lv_event_t * e);
extern lv_obj_t *ui_InputArea;
extern lv_obj_t *ui_MaxHealthSubScreen;
void ui_event_MHPad_NumPad( lv_event_t * e);
extern lv_obj_t *ui_MHPad;
extern lv_obj_t *ui_MHInputDisplay;
extern lv_obj_t *ui_CurrentHealthSubScreen;
void ui_event_CHPad_NumPad( lv_event_t * e);
extern lv_obj_t *ui_CHPad;
extern lv_obj_t *ui_CHInputDisplay;
extern lv_obj_t *ui_TempSubScreen;
void ui_event_TempPad_NumPad( lv_event_t * e);
extern lv_obj_t *ui_TempPad;
extern lv_obj_t *ui_TempInputDisplay;
extern lv_obj_t *ui_NameSubScreen;
void ui_event_NameBoard_NumPad( lv_event_t * e);
extern lv_obj_t *ui_NameBoard;
extern lv_obj_t *ui_NameBoardDisplay;
void ui_event_XButton( lv_event_t * e);
extern lv_obj_t *ui_XButton;
extern lv_obj_t *ui_xButtonText;
void ui_event_HealDamagePad_NumPad( lv_event_t * e);
extern lv_obj_t *ui_HealDamagePad;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Image1;
extern lv_obj_t *uic_Image1;
extern lv_obj_t *uic_Heal_Button;

// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
extern lv_obj_t *ui_SettingScreen;
extern lv_obj_t *ui_AllSettingsContainer;
extern lv_obj_t *ui_HPColor;
extern lv_obj_t *ui_HPColorChoice;
extern lv_obj_t *ui_HPLabel;
extern lv_obj_t *ui_TempHPColor;
extern lv_obj_t *ui_THPColorChoice;
extern lv_obj_t *ui_THPLabel;
void ui_event_DeleteButton1( lv_event_t * e);
extern lv_obj_t *ui_DeleteButton1;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_PlayerInfo;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_currentProfile;
extern lv_obj_t *ui_CPText;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_CurrentCharacter;
extern lv_obj_t *ui_CCText;
void ui_event_Back2( lv_event_t * e);
extern lv_obj_t *ui_Back2;
extern lv_obj_t *ui_arrow1;
extern lv_obj_t *ui_ConfirmDeleteContainer;
extern lv_obj_t *ui_Label20;
void ui_event_Button13( lv_event_t * e);
extern lv_obj_t *ui_Button13;
extern lv_obj_t *ui_Label21;
void ui_event_Button14( lv_event_t * e);
extern lv_obj_t *ui_Button14;
extern lv_obj_t *ui_Label22;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Image1;

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_wood_paneling_png);   // assets/wood_paneling.png
LV_IMG_DECLARE( ui_img_plus_png);   // assets/plus.png
LV_IMG_DECLARE( ui_img_278415715);   // assets/setting (1).png
LV_IMG_DECLARE( ui_img_arrow_png);   // assets/arrow.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
